// This file is generated by case-study-index.script.ts. Do not edit manually.
import { DatedCaseStudyMetadata } from "@/types/case_study.types";

const data: DatedCaseStudyMetadata[] = [
  {
    "id": "anthony_king_website",
    "title": "Anthony King",
    "date": "2024-05-10T00:00:00.000Z",
    "project_type": "Website",
    "role": "Full Design",
    "description": "Anthony King, a mortgage broker in Montreal, entrusted me with creating a professional website to strengthen his credibility and attract new clients.",
    "url": "https://anthonyking.ca",
    "score": 8,
    "tags": [
      "Finance",
      "Design",
      "Frontend"
    ],
    "hash": "bd4d8d0fb6b3be2802cbaf521cb4700dc64cac76227ce6feab3eff834e6f03ab",
    "last_updated": "2025-09-22"
  },
  {
    "id": "cactusoft_app",
    "title": "Cactusoft",
    "date": "2024-08-25T00:00:00.000Z",
    "project_type": "Web Application",
    "role": "Lead UX Designer",
    "description": "Cactusoft develops an all-in-one construction management app, aiming to modernize it, simplify complex problems, and improve the developer experience with reusable designs.",
    "url": "https://cactusoft.app",
    "score": 7,
    "tags": [
      "Design System",
      "Developer Experience",
      "Problem Solving",
      "Communication"
    ],
    "active": true,
    "hash": "0bd8e64a5cf0249173dc8d4e846716dfae71f2d717e14d46ecf461f56fa5a960",
    "last_updated": "2025-09-22"
  },
  {
    "id": "eosnation_ens",
    "title": "EOS Name Service",
    "date": "2023-05-01T00:00:00.000Z",
    "project_type": "Web Application",
    "role": "Product Definition, Design",
    "description": "EOS Name Service is a platform that allows associating EOS and Wax addresses with unique names, similar to a domain name service for websites.",
    "url": "https://eosnameservice.io",
    "score": 6,
    "tags": [
      "Web3, Blockchain",
      "Project Management",
      "Design"
    ],
    "hash": "5f004d5ff91bf7f6122301110d0941173707058e3e53f52fc01dc3a7319ec8c0",
    "last_updated": "2025-09-22"
  },
  {
    "id": "eosnation_spyglass",
    "title": "Spyglass",
    "date": "2023-01-01T00:00:00.000Z",
    "project_type": "Web Application",
    "role": "Full Design",
    "description": "Spyglass brings transparency to blockchain transaction processing before they appear on public networks, thanks to direct integration with indexers.",
    "url": "https://spyglass.network",
    "score": 4,
    "tags": [
      "Web3, Blockchain",
      "Product Management",
      "Design",
      "Frontend"
    ],
    "hash": "fab47e82ccfc771ac3153055c08166a564acb2a215e9c116cf1c9d49615c314f",
    "last_updated": "2025-09-22"
  },
  {
    "id": "fanslab_webapp",
    "title": "Fanslab",
    "date": "2020-07-20T00:00:00.000Z",
    "project_type": "Web Application",
    "role": "Lead Developer",
    "description": "Fanslab was a smart community platform that enabled several large companies to continue their conferences in digital format during the pandemic.",
    "url": "https://drive.google.com/file/d/1LxtnU_kqo1KnYF4QZSPGDbF4Hqd4Uo0O/view?usp=drive_link",
    "score": 6,
    "tags": [
      "Event Management",
      "Digital Strategy",
      "Project Management",
      "Frontend"
    ],
    "hash": "f3ff42910b5168988050a1d0c226c42135535572b593d48a304d4841a7b83189",
    "last_updated": "2025-09-22"
  },
  {
    "id": "monark",
    "title": "Monark",
    "date": "2025-03-15T00:00:00.000Z",
    "project_type": "Company",
    "role": "Co-Founder & CTO",
    "description": "Monark is a positive Web3 player aiming to solve several major challenges in the field, including education, talent acquisition, and industry integration.",
    "url": "https://monark.io",
    "score": 8,
    "tags": [
      "Startup",
      "Web3, Blockchain",
      "Entrepreneurship",
      "Digital Strategy",
      "Project Management",
      "Design",
      "Frontend"
    ],
    "hash": "1647055a49fb06cd5dd810bac129bf0b28c7a77ada0cdc5d3620a23e1bafc914",
    "last_updated": "2025-09-22"
  },
  {
    "id": "oreus",
    "title": "Oreus",
    "date": "2022-11-01T00:00:00.000Z",
    "project_type": "Company",
    "role": "Co-founder & CTO",
    "description": "Oreus worked in software development services. Although short-lived, this experience provided valuable lessons and strong partnerships.",
    "score": 7,
    "tags": [
      "Startup",
      "Software Services",
      "Entrepreneurship",
      "Digital Strategy",
      "Design",
      "Frontend"
    ],
    "hash": "6c9371eb8f3edccb97ce44510c4960e4ae6c5afe02a4cf1e27d482bcc7d6626b",
    "last_updated": "2025-09-22"
  },
  {
    "id": "oreus_balance_website",
    "title": "Oreus Balance",
    "date": "2021-07-01T00:00:00.000Z",
    "project_type": "Web Application",
    "role": "Full Design",
    "description": "Oreus Balance is the idea that led to the founding of Oreus. Born from a need for transparency in our personal finances.",
    "score": 6,
    "tags": [
      "Startup",
      "Finance",
      "Onboarding",
      "Design"
    ],
    "hash": "cc015e4c6550e8b0baffb44de9be1dcf47a22d9794bdd075ecb244a821dfb624",
    "last_updated": "2025-09-22"
  },
  {
    "id": "pinax_app",
    "title": "Pinax App",
    "date": "2023-11-18T00:00:00.000Z",
    "project_type": "Web Application",
    "role": "Full Design",
    "description": "Pinax works in blockchain data indexing, contributing to The Graph infrastructure. The company wanted a platform for accessing its data.",
    "url": "https://app.pinax.network",
    "score": 7,
    "tags": [
      "Web3, Blockchain",
      "Product Management",
      "Design",
      "Frontend"
    ],
    "hash": "3a9153cc5c2c2bea83e94bb3b12f786ef2d74f318fa5469b76462e82c1ce2574",
    "last_updated": "2025-09-22"
  },
  {
    "id": "pinax_website",
    "title": "Pinax Website",
    "date": "2023-08-01T00:00:00.000Z",
    "project_type": "Website",
    "role": "Full Design",
    "description": "Pinax works in blockchain data indexing. The company entrusted me with the mandate for design, development, and maintenance.",
    "url": "https://pinax.network",
    "score": 8,
    "tags": [
      "Web3, Blockchain",
      "Design",
      "Frontend"
    ],
    "hash": "7ad0659a3639ea42f494a6c007107d5ae72c7663fd78d45032b3f92102333bae",
    "last_updated": "2025-09-22"
  }
];

export default data;
