// This file is generated by case-study-index.script.ts. Do not edit manually.
import { DatedCaseStudyMetadata } from "@/types/case_study.types";

const data: DatedCaseStudyMetadata[] = [
  {
    "id": "anthony_king_website",
    "title": "Anthony King Site Web",
    "date": "2024-05-10T00:00:00.000Z",
    "role": "Conception complète",
    "description": "Anthony King est un courtier hypothécaire de la région de Montréal. Il m'a approché pour bâtir son site web professionnel.",
    "url": "https://anthonyking.ca",
    "score": 8,
    "hash": "5d93a1797db0c72cc8c9defaa75b33f162dd2f63c81a341a1ce1703838d663da",
    "last_updated": "2025-09-18"
  },
  {
    "id": "eosnation_ens",
    "title": "EOS Name Service",
    "date": "2023-05-01T00:00:00.000Z",
    "role": "Design & Gestion",
    "description": "EOS Name Service est une plateforme permettant d'associer des adresses EOS et Wax à des noms uniques, comme le permettrait un service de noms de domaine pour des sites web.",
    "url": "https://eosnameservice.io",
    "score": 6,
    "hash": "bff1565d37d19f5ce30b7431363355b888b767af1f0d08ad2ecea25075c18d74",
    "last_updated": "2025-09-18"
  },
  {
    "id": "eosnation_spyglass",
    "title": "Spyglass",
    "date": "2023-01-01T00:00:00.000Z",
    "role": "Conception complète",
    "description": "Dans cette étude de cas, je partagerai avec vous mes principales leçons dans la construction de la plateforme Spyglass Lost Transactions.",
    "url": "https://spyglass.network",
    "score": 4,
    "hash": "7376c08379b2f7d967da88d596c134db3dc7d38352c52becde836a9b7b969098",
    "last_updated": "2025-09-18"
  },
  {
    "id": "fanslab_webapp",
    "title": "Fanslab",
    "date": "2020-07-20T00:00:00.000Z",
    "role": "Développeur principal",
    "description": "Dans cette étude de cas, je partagerai avec vous mes principales leçons dans la construction de la plateforme Web de Fanslab.",
    "url": "https://www.youtube.com/watch?v=J7fdJnQfusU",
    "score": 6,
    "hash": "5db892503f589c86e8f7d82e4105123ac10dbabd5c239994d05d3534d409d841",
    "last_updated": "2025-09-18"
  },
  {
    "id": "monark",
    "title": "Monark",
    "date": "2025-03-15T00:00:00.000Z",
    "role": "Co-Fondateur, CTO",
    "description": "Dans cette étude de cas, je partagerai avec vous mes principales leçons apprises au cours de mon mandat chez Monark en tant que CTO.",
    "url": "https://monark.io",
    "score": 8,
    "hash": "98750f3d09d818f0c521ddbbf60dc1f111e05383f6fe5708f82d92b4978ced6b",
    "last_updated": "2025-09-18"
  },
  {
    "id": "oreus",
    "title": "Oreus",
    "date": "2022-11-01T00:00:00.000Z",
    "role": "Co-fondateur, CTO",
    "description": "Dans cette étude de cas, je partagerai avec vous mes principales leçons dans la construction de ma société de services logiciels, Oreus.",
    "score": 7,
    "hash": "ba37af77ddd4d84e343c9c3555cacfc03e9c9757559277ffd260d2862d5b98ef",
    "last_updated": "2025-09-18"
  },
  {
    "id": "oreus_balance_website",
    "title": "Oreus Balance",
    "date": "2021-07-01T00:00:00.000Z",
    "role": "Conception complète",
    "description": "Dans cette étude de cas, je partagerai avec vous mes principales leçons dans la conception d'Oreus Balance, une application Web de finances personnelles.",
    "score": 6,
    "hash": "498b695761dd97404b0b86ae465ae8d8cfcdba5e5b7b1e68a3a71bcaf76a69d5",
    "last_updated": "2025-09-18"
  },
  {
    "id": "pinax_app",
    "title": "Pinax App",
    "date": "2023-11-18T00:00:00.000Z",
    "role": "Développement Frontend",
    "description": "Dans cette étude de cas, je partagerai avec vous mes principales leçons dans la construction de la plateforme Web de Pinax.",
    "url": "https://app.pinax.network",
    "score": 7,
    "hash": "2ad08cdfe3c5e17fbbc6d21300312f1544d46eb68260b8c9a944a89010d0a78a",
    "last_updated": "2025-09-18"
  },
  {
    "id": "pinax_website",
    "title": "Pinax Website",
    "date": "2023-08-01T00:00:00.000Z",
    "role": "Conception complète",
    "description": "Dans cette étude de cas, je partagerai avec vous mes principales leçons dans la construction du site Web de Pinax.",
    "url": "https://pinax.network",
    "score": 8,
    "hash": "8727d0008c631d191b9162400ac8ef3db7721a4f8e87c86ffb9cf6f0685af3ad",
    "last_updated": "2025-09-18"
  }
];

export default data;
