// This file is generated by articles-index.script.ts. Do not edit manually.
import { DatedArticleMetadata } from "@/types/article.types";

const data: DatedArticleMetadata[] = [
  {
    "id": "interview-mistakes-i-ve-seen-people-do",
    "title": "Interview Mistakes I've Seen People Do",
    "date": "2022-01-11T00:00:00.000Z",
    "img": "interview.webp",
    "img_alt": "Interview between two persons in a meeting room",
    "img_src": "https://unsplash.com/fr/photos/femme-en-chemise-blanche-a-manches-longues-assise-sur-un-canape-rouge-1A8yP_5msac",
    "excerpt": "I've interviewed a few people and had to choose the best candidates for a software engineering role. Here are some of the mistakes I've seen people do and how to avoid them.",
    "read_time_seconds": 270,
    "tags": [
      "Career",
      "Management"
    ],
    "hash": "7f8ff1d23b22af69d56cd1838ed6f6625414c89d11813a67803f83e5a6393ea2",
    "last_updated": "2025-09-22"
  },
  {
    "id": "the-one-common-problem-in-software-engineering-teams",
    "title": "The One Common Problem in Software Engineering Teams",
    "date": "2022-01-01T00:00:00.000Z",
    "img": "screaming_in_mic.webp",
    "img_alt": "Child screaming in a microphone",
    "img_src": "https://unsplash.com/fr/photos/garcon-chantant-sur-le-microphone-avec-filtre-anti-pop-ASKeuOZqhYU",
    "excerpt": "Communication; know the different challenges and how to address them.",
    "read_time_seconds": 280,
    "tags": [
      "Career",
      "Management"
    ],
    "hash": "77e6e615037252e71ddd20064de11173e7d3a9813858f2fc78db7af8b481ec1e",
    "last_updated": "2025-09-22"
  }
];

export default data;
