// This file is generated by articles-index.script.ts. Do not edit manually.
import { DatedArticleMetadata } from "@/types/article.types";

const data: DatedArticleMetadata[] = [
  {
    "id": "interview-mistakes-i-ve-seen-people-do",
    "title": "Interview Mistakes I've Seen People Do",
    "date": "2022-01-11T00:00:00.000Z",
    "img": "interview.webp",
    "img_alt": "Interview between two persons in a meeting room",
    "img_src": "https://unsplash.com/fr/photos/femme-en-chemise-blanche-a-manches-longues-assise-sur-un-canape-rouge-1A8yP_5msac",
    "excerpt": "I've interviewed a few people and had to choose the best candidates for a software engineering role. Here are some of the mistakes I've seen people do and how to avoid them.",
    "read_time_seconds": 270,
    "tags": [
      "Article",
      "Career",
      "Management"
    ],
    "hash": "38d4b3a7258888501d0767769be4b46bc683c9f988d01927f313af8a34380124",
    "last_updated": "2025-09-22"
  },
  {
    "id": "the-one-common-problem-in-software-engineering-teams",
    "title": "The One Common Problem in Software Engineering Teams",
    "date": "2022-01-01T00:00:00.000Z",
    "img": "screaming_in_mic.webp",
    "img_alt": "Child screaming in a microphone",
    "img_src": "https://unsplash.com/fr/photos/garcon-chantant-sur-le-microphone-avec-filtre-anti-pop-ASKeuOZqhYU",
    "excerpt": "Communication; know the different challenges and how to address them.",
    "read_time_seconds": 280,
    "tags": [
      "Article",
      "Career",
      "Management"
    ],
    "hash": "fe9edfc897d12b4e3b6eacd42ffcdba40f0f413e920b756c39d89982b76bdcbf",
    "last_updated": "2025-09-22"
  }
];

export default data;
