import { locales } from "@/i18n.config";
import fs from "fs";
import path from "path";
import { DatedArticleMetadata } from "@/types/article.types";
import {
  getMetadataFromFile,
  getContentSubdirectories,
  generateHash,
} from "../utils/index.utils";

type PreviousIndex = Record<string, Partial<DatedArticleMetadata>>;

function generateArticlesIndex(
  locale: string,
  previousIndex: PreviousIndex = {}
): DatedArticleMetadata[] {
  const articlesDir = path.join(
    process.cwd(),
    `content/${locale}/articles`
  );
  if (!fs.existsSync(articlesDir)) {
    console.error(`Directory not found: ${articlesDir}`);
    return [];
  }

  const subdirectories = getContentSubdirectories(articlesDir);
  return subdirectories
    .map((subdir) => {
      const pagePath = path.join(articlesDir, subdir, "page.mdx");
      console.log(`Processing article page: ${pagePath}`);
      if (fs.existsSync(pagePath)) {
        const metadata = getMetadataFromFile(pagePath);
        if (metadata) {
          const hash = generateHash(metadata);
          const previousEntry = previousIndex[metadata.id] || {};
          const lastUpdated =
            hash !== previousEntry.hash
              ? new Date().toISOString().split("T")[0]
              : previousEntry.last_updated ||
              new Date().toISOString().split("T")[0];
          if (metadata) {
            // DatedArticleMetadata expects date as Date, but we store as string (ISO) in JSON
            return {
              id: metadata.id,
              title: metadata.title,
              date: metadata.date,
              img: metadata.img,
              img_alt: metadata.img_alt,
              img_src: metadata.img_src,
              excerpt: metadata.excerpt,
              read_time_seconds: metadata.read_time_seconds,
              tags: metadata.tags,
              hash,
              last_updated: lastUpdated,
            };
          }
        }
        return null;
      }
    })
    .filter((article): article is NonNullable<typeof article> => article !== null);
}

console.log("Starting articles index generation...");

locales.forEach((locale) => {
  console.log(`Processing locale: ${locale}...`);
  const articlesIndex = generateArticlesIndex(locale);
  // Write to content/${locale}/articles/index.ts
  const outputFilePath = path.join(
    process.cwd(),
    `content/${locale}/articles/index.ts`
  );
  const fileContent = `// This file is generated by articles-index.script.ts. Do not edit manually.\nimport { DatedArticleMetadata } from \"@/types/article.types\";\n\nconst data: DatedArticleMetadata[] = ${JSON.stringify(
    articlesIndex,
    null,
    2
  )};\n\nexport default data;\n`;
  console.log(`Writing output file to: ${outputFilePath}`);
  fs.writeFileSync(outputFilePath, fileContent);
});

console.log("Articles index generation completed.");
