// This file is generated by articles-index.script.ts. Do not edit manually.
import { DatedArticleMetadata } from "@/types/article.types";

const data: DatedArticleMetadata[] = [
  {
    "id": "interview-mistakes-i-ve-seen-people-do",
    "title": "Erreurs d'entrevue que j'ai vues des gens commettre",
    "date": "2022-01-11T00:00:00.000Z",
    "img": "interview.webp",
    "img_alt": "Entretien entre deux personnes dans une salle de réunion",
    "img_src": "https://unsplash.com/fr/photos/femme-en-chemise-blanche-a-manches-longues-assise-sur-un-canape-rouge-1A8yP_5msac",
    "excerpt": "J'ai interviewé quelques personnes et j'ai dû choisir les meilleurs candidats pour un rôle de génie logiciel. Voici quelques-unes des erreurs que j'ai vues faire et comment les éviter.",
    "read_time_seconds": 270,
    "tags": [
      "Carrière",
      "Gestion"
    ],
    "hash": "60b273e2a04f97521b32d4dd0a83111eedd62571026d19d5303036e4c644bc36",
    "last_updated": "2025-09-18"
  },
  {
    "id": "the-one-common-problem-in-software-engineering-teams",
    "title": "Le problème commun aux équipes de développement logiciel",
    "date": "2022-01-01T00:00:00.000Z",
    "img": "screaming_in_mic.webp",
    "img_alt": "Enfant criant dans un microphone",
    "img_src": "https://unsplash.com/fr/photos/garcon-chantant-sur-le-microphone-avec-filtre-anti-pop-ASKeuOZqhYU",
    "excerpt": "La communication; connaître les différents défis et comment les relever.",
    "read_time_seconds": 280,
    "tags": [
      "Carrière",
      "Gestion"
    ],
    "hash": "6d038bc678bac107b1487716c2b80fcaf08667ef8af1e58c1ed938417ed0bf66",
    "last_updated": "2025-09-18"
  }
];

export default data;
