// This file is generated by articles-index.script.ts. Do not edit manually.
import { DatedArticleMetadata } from "@/types/article.types";

const data: DatedArticleMetadata[] = [
  {
    "id": "interview-mistakes-i-ve-seen-people-do",
    "title": "Erreurs d'entrevue que j'ai vues des gens commettre",
    "date": "2022-01-11T00:00:00.000Z",
    "img": "interview.webp",
    "img_alt": "Entretien entre deux personnes dans une salle de réunion",
    "img_src": "https://unsplash.com/fr/photos/femme-en-chemise-blanche-a-manches-longues-assise-sur-un-canape-rouge-1A8yP_5msac",
    "excerpt": "J'ai interviewé plusieurs personnes pour trouver les meilleurs candidats afin de combler des postes de génie logiciel. Voici quelques-unes des erreurs que j'ai vues et comment les éviter.",
    "read_time_seconds": 270,
    "tags": [
      "Carrière",
      "Gestion"
    ],
    "hash": "f33c26a34d7fa251d1c39b8e731f12ff2d2d5d23932287e15b4c27524f5948e2",
    "last_updated": "2025-09-19"
  },
  {
    "id": "the-one-common-problem-in-software-engineering-teams",
    "title": "Le problème commun aux équipes de développement logiciel",
    "date": "2022-01-01T00:00:00.000Z",
    "img": "screaming_in_mic.webp",
    "img_alt": "Enfant criant dans un microphone",
    "img_src": "https://unsplash.com/fr/photos/garcon-chantant-sur-le-microphone-avec-filtre-anti-pop-ASKeuOZqhYU",
    "excerpt": "La communication; connaître les différents défis et comment les relever.",
    "read_time_seconds": 280,
    "tags": [
      "Carrière",
      "Gestion"
    ],
    "hash": "6d038bc678bac107b1487716c2b80fcaf08667ef8af1e58c1ed938417ed0bf66",
    "last_updated": "2025-09-19"
  }
];

export default data;
