// This file is generated by case-study-index.script.ts. Do not edit manually.
import { DatedCaseStudyMetadata } from "@/types/case_study.types";

const data: DatedCaseStudyMetadata[] = [
  {
    "id": "anthony_king_website",
    "title": "Anthony King",
    "date": "2024-05-10T00:00:00.000Z",
    "project_type": "Site web",
    "role": "Conception complète",
    "description": "Anthony King, courtier hypothécaire à Montréal, m'a confié la création d'un site web professionnel pour renforcer sa crédibilité et attirer de nouveaux clients.",
    "url": "https://anthonyking.ca",
    "score": 8,
    "tags": [
      "Finance",
      "Design",
      "Frontend"
    ],
    "hash": "ad709eb08fa23f8e3f90945ec9426be0548403a5f3a68cd49715a14707f4db41",
    "last_updated": "2025-09-22"
  },
  {
    "id": "cactusoft_app",
    "title": "Cactusoft",
    "date": "2024-08-25T00:00:00.000Z",
    "project_type": "Application web",
    "role": "UX designer principal",
    "description": "Cactusoft développe une application de gestion de chantier tout-en-un et cherchait à moderniser l'app, simplifier des problèmes complexes et améliorer l'expérience des développeurs avec des designs réutilisables.",
    "url": "https://cactusoft.app",
    "score": 7,
    "tags": [
      "Système de design",
      "Expérience développeur",
      "Résolution de problème",
      "Communication"
    ],
    "active": true,
    "hash": "3e09cde3fb63554caa152d0cd9c4841c79f28e340a9b3ede2f8579d3aafab951",
    "last_updated": "2025-09-22"
  },
  {
    "id": "eosnation_ens",
    "title": "Registre de noms EOS",
    "date": "2023-05-01T00:00:00.000Z",
    "project_type": "Application web",
    "role": "Définition de produit & Design",
    "description": "EOS Name Service est une plateforme permettant d'associer des adresses EOS et Wax à des noms uniques, comme le permettrait un service de noms de domaine pour des sites web.",
    "url": "https://eosnameservice.io",
    "score": 6,
    "tags": [
      "Web3, Blockchain",
      "Gestion de projet",
      "Design"
    ],
    "hash": "439ea389b00d6d515679da089f148aff0e007165b1897a4e9901c4f23bd8be36",
    "last_updated": "2025-09-22"
  },
  {
    "id": "eosnation_spyglass",
    "title": "Spyglass",
    "date": "2023-01-01T00:00:00.000Z",
    "project_type": "Application web",
    "role": "Conception complète",
    "description": "Spyglass apporte de la transparence dans le traitement de transactions Blockchain avant leur apparission sur les réseaux publiques, grâce à une intégration directe aux indexeurs.",
    "url": "https://spyglass.network",
    "score": 4,
    "tags": [
      "Web3, Blockchain",
      "Gestion de produit",
      "Design",
      "Frontend"
    ],
    "hash": "12881e4ba0bd26d71309a897efc0c69f04644de027b0ab85644cabd78ab71802",
    "last_updated": "2025-09-22"
  },
  {
    "id": "fanslab_webapp",
    "title": "Fanslab",
    "date": "2020-07-20T00:00:00.000Z",
    "project_type": "Application web",
    "role": "Développeur principal",
    "description": "Fanslab était une plateforme de communauté intelligente ayant permis à plusieurs grandes entreprises de continuer leurs conférences en format numérique durant la pandémie.",
    "url": "https://drive.google.com/file/d/1LxtnU_kqo1KnYF4QZSPGDbF4Hqd4Uo0O/view?usp=drive_link",
    "score": 6,
    "tags": [
      "Évènementiel",
      "Stratégie numérique",
      "Gestion de projet",
      "Frontend"
    ],
    "hash": "b11c032b8baa2d08c50817a3f6ea81eabfdacbda1f1b5d195d897cb75d0387ab",
    "last_updated": "2025-09-22"
  },
  {
    "id": "monark",
    "title": "Monark",
    "date": "2025-03-15T00:00:00.000Z",
    "project_type": "Entreprise",
    "role": "Co-Fondateur & CTO",
    "description": "Monark est un acteur positif du Web3 visant à résoudre plusieurs enjeux majeurs du domaine, dont la formation, l'acquisition de talent et l'intégration en industrie.",
    "url": "https://monark.io",
    "score": 8,
    "tags": [
      "Startup",
      "Web3, Blockchain",
      "Entrepreneuriat",
      "Stratégie numérique",
      "Gestion de projet",
      "Design",
      "Frontend"
    ],
    "hash": "8055366a3525d86287cfb6558fc72e9fac0b2ed4c00f04a8a3686ddabca64e8a",
    "last_updated": "2025-09-22"
  },
  {
    "id": "oreus",
    "title": "Oreus",
    "date": "2022-11-01T00:00:00.000Z",
    "project_type": "Entreprise",
    "role": "Co-fondateur & CTO",
    "description": "Oreus oeuvrait dans le service de développement logiciel. Bien que de trop courte durée, cette expérience a forgé de solides apprentissages et partenariats.",
    "score": 7,
    "tags": [
      "Startup",
      "Service logiciel",
      "Entrepreneuriat",
      "Stratégie numérique",
      "Design",
      "Frontend"
    ],
    "hash": "4b1eacb5cc47cdd93f68811470ef50c21648989650fd884daa766f998f0e1fe6",
    "last_updated": "2025-09-22"
  },
  {
    "id": "oreus_balance_website",
    "title": "Oreus Balance",
    "date": "2021-07-01T00:00:00.000Z",
    "project_type": "Application web",
    "role": "Conception complète",
    "description": "Oreus Balance est l'idée qui a lancée la fondation d'Oreus. Née d'un besoin de transparence sur nos finances personnelles.",
    "score": 6,
    "tags": [
      "Startup",
      "Finance",
      "Onboarding",
      "Design"
    ],
    "hash": "e59508ef8a0274ae26ba46e41e3f8eda281e345ee9e48ff4fd7cbec1fb55ec00",
    "last_updated": "2025-09-22"
  },
  {
    "id": "pinax_app",
    "title": "Pinax App",
    "date": "2023-11-18T00:00:00.000Z",
    "project_type": "Application web",
    "role": "Conception complète",
    "description": "Pinax oeuvre dans l'indexation de données blockchain, contribuant à l'infrastructure The Graph, l'entreprise désirait une plateforme pour l'accès à ses données.",
    "url": "https://app.pinax.network",
    "score": 7,
    "tags": [
      "Web3, Blockchain",
      "Gestion de produit",
      "Design",
      "Frontend"
    ],
    "hash": "b7063836532359cb83f8f817a42d414e4f46bfedece4e55e34b09a8bb1f318bb",
    "last_updated": "2025-09-22"
  },
  {
    "id": "pinax_website",
    "title": "Pinax Website",
    "date": "2023-08-01T00:00:00.000Z",
    "project_type": "Site web",
    "role": "Conception complète",
    "description": "Pinax oeuvre dans l'indexation de données blockchain, l'entreprise m'a confié le mandat de design, développement et maintenance.",
    "url": "https://pinax.network",
    "score": 8,
    "tags": [
      "Web3, Blockchain",
      "Design",
      "Frontend"
    ],
    "hash": "ce6479ca7bc3dc5f0f43eff45dc046c0911c7c2c820e1181840f795ace7f4f2c",
    "last_updated": "2025-09-22"
  }
];

export default data;
